todo_tracker/config/routes.rb
TodoTracker::Application.routes.draw do
resources :todos
end

todo_tracker/app/models/task.rb
class Task < ActiveRecord::Base

end

todo_tracker/app/models/todo.rb
class Todo < ActiveRecord::Base
end

todo_tracker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :set_task, only: [:show, :edit, :update, :destroy]

	def show
	end

	def index
		@tasks = Task.all
	end

	def new
		@task = Task.new
	end

	def create 
		@task = Task.new(task_params)
		if @task.save
			redirect_to @task
		else
			render action: 'new'
		end
	end

	def edit 
	end

	def update 
		if @task.update(task_params)
			redirect_to @task
		else
			render action: 'edit'
		end
	end

	def destroy
		@task.destroy
		redirect_to tasks_url
	end

	private

	def set_task
		@task = Task.find(params[:id])
	end

	def task_params
		params.require(:task).permit(:name, :description, :complete, :due)
	end

end

todo_tracker/app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :set_todo, only: [:show, :edit, :update, :destroy]
	def show
	end
	def index
		@todos = Todo.all
	end
	def create
		@todo = Todo.new(todo_params)

		if @todo.save
			redirect_to @todo
		else
			render action: 'new'
		end
	end
	def new
		@todo = Todo.new
	end
	def update
		if @todo.update(todo_params)
			redirect_to @todo
		else
			redner action: 'edit'
		end
	end
	def edit
	end
	def destroy
		@todo.destroy
		redirect_to todos_url
	end

	private

	def set_todo
		@todo = Todo.find(params[:id])
	end
	def todo_params
		params.require(:todo).permit(:task, :complete, :due_date, :description)
	end
end

todo_tracker/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
	<%= f.label :name %><%= f.text_field :name %><br/>
	<%= f.label :description %><%= f.text_area :description %><br/>
	<%= f.label :due %><%= f.text_field :due %><br/>
	<%= f.label :complete %><%= f.check_box :complete %><br/>
	<%= f.submit %>
	<% end %>	

todo_tracker/app/views/tasks/edit.html.erb
<h2>Edit task</h2>


<%= render 'form' %>

todo_tracker/app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
<h3><%= link_to task.name, task %></h3>Description: <%= task.description %><br/>
Complete? <%= task.complete %><br/>
Due: <%= task.due %><br/><br/>
<%= link_to "Edit task", edit_task_path(task) %><br/>
<%= link_to "Delete task", task, method: :delete, data: { confirm: 'Are you sure you want to delete this task?'} %><br/>
<br/><br/>
<hr>
<% end %>



<br/>
<%= link_to "Add a new task", new_task_path %>

todo_tracker/app/views/tasks/new.html.erb
<h2>Add a new task</h2>


<%= render 'form' %>

todo_tracker/app/views/tasks/show.html.erb
<div><h3><%= @task.name %></h3></div><br/>
<div>Description: <%= @task.description %></div><br/>
<div>Complete? <%= @task.complete %></div><br/>
<div>Due Date: <%= @task.due %></div><br/>


<%= link_to "Edit task", edit_task_path(@task) %><br/>
<%= link_to "Delete task", @task, method: :delete, data: { confirm: 'Are you sure you want to delete this task?'} %><br/><br/>

todo_tracker/app/views/todos/_form.html.erb
<div class="todo_form">
<div><%= form_for(@todo) do |f| %>
	<div><%= f.label :task %><%= f.text_field :task %></div>
	<div><%= f.label :description %><%= f.text_area :description %></div>
	<div><%= f.label :complete %><%= f.check_box :complete %></div>
	<div><%= f.label :due_date %><%= f.date_field :due_date %></div>
	<div><%= f.submit %> </div>
<% end %>
</div>

todo_tracker/app/views/todos/index.html.erb
<div class="todos">
<% @todos.each do |todo| %>
	<h3> <%= todo.task%> </h3>
	<%= todo.complete %>
	<%= link_to todo.task, todo %>
	<%= todo.description %>
	<%= link_to "edit todo", edit_todo_path(todo) %>
	<%= link_to "destroy todo", todo, method: :delete, data:{confirm: "are you sure?"} %>
<% end %>
</div>
<div> <%= link_to "new todo", new_todo_path %> </div>

todo_tracker/app/views/todos/new.html.erb
<h1>new todo</h1>
<%= render 'form' %>

todo_tracker/app/views/todos/show.html.erb
<div class="todo">
	<div> <%=@todo.task %></div>
	<div> <%=@todo.due_date %></div>
	<div> <%=@todo.complete %></div>
	<div> <%=@todo.description %></div>
</div>
<%= link_to "back", todos_path %>