config/routes.rb
ToDoList::Application.routes.draw do
  root 'todos#index'
  resources :todos do
    member do
      put 'complete'
    end
  end

  

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  
  def show
  end

  def index
    @todos = Todo.all
    @todo = Todo.new
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render action 'new'
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to @todo
    else
      render action 'edit'
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    completed = Todo.find(params[:id])
    completed.flag = true
    completed.save
    redirect_to todos_path
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :flag, :deadline)
  end
end

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
	<div class="field">
		<%= f.label :name %><%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %><%= f.text_field :description %>
	</div>
	<div class="field">
		<%= f.label :deadline %><%= f.date_select :deadline %>
	</div>
	<div class="field">
	<br />
	<%= f.submit %>
	</div>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>
<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Tasks</h1>

<div class="tasks">


	<h3>To Do</h3>
	<% @todos.each do |todo| %>
		<% if todo.flag == false %>
			<div class="to-do">
				<div class="left">
					<%= todo.name %> | <%= todo.deadline %>
				</div>
				<div class="right">
				<%= link_to "done", complete_todo_path(todo), method: :put %> | <%= link_to "delete", todo, method: :delete, data: { confirm: "Delete this task?"} %>
				</div>
			</div>
		<% end %>
	<% end %>

	<h3>Add a task:</h3>
<%= form_for(@todo) do |f| %>
	<div class="field">
		Task:<%= f.text_field :name %> Deadline:<%= f.date_select :deadline %>
		<%= f.submit %>
	</div>
<% end %>

		<h3>Completed</h3>
	<% @todos.each do |todo| %>
		<% if todo.flag == true %>
			<div class="completed">
				<div class="left">
					<strike><%= todo.name %> | <%= todo.deadline %></strike>
				</div>
			</div>
		<% end %>
	<% end %>

</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>
<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Task</h1>

<%= @todo.name %><br />
Do by <%= @todo.deadline %><br />
<%= @todo.description %>
</div>
<br><br />
<%= link_to "Task List" , todos_path %>