to_do_list/config/routes.rb
ToDoList::Application.routes.draw do

  root 'lists#index'
  resources :lists 

  

  

end

to_do_list/app/models/list.rb
class List < ActiveRecord::Base 
end 

to_do_list/app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :set_list, only: [:show , :edit , :update, :destroy]

	def show 
	end 

	def index 
		@lists = List.all 
	end 

	def new 
		@list = List.new 
	end 

	def create
		@list = List.new(list_params)
		if @list.save 
			redirect_to @list 
		else 
			render action: 'new'
		end 
	end

	def edit
	end 

	def update 
		if @list.update(list_params)
			redirect_to @list
		else 
			render action: 'edit'
		end 
	end 

	def destroy
		@list = List.destroy
		redirect_to lists_url 
	end 

	private 

	def set_list
		@list = List.find(params[:id])
	end 

	def list_params
		params.require(:list).permit(:task, 
			:due_date, :created_at, :owner, :complete, :notes, :catagory, :days_to_complete)
	end 

end

to_do_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

to_do_list/app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %> 
	<div><%=f.label :task %> <%=f.text_field :task %></div>
	<div><%=f.label :notes %> <%=f.text_field :notes %></div>
	<div><%=f.label :due_date %> <%=f.text_field :due_date %></div>
	<div><%=f.label :created_at %> <%=f.text_field :owner%></div>
	<div><%=f.label :complete %> <%=f.check_box :complete %></div>
	<div><%=f.label :owner %> <%=f.text_field :owner %></div>
	<div><%=f.label :catagory %> <%=f.text_field :catagory %></div>
	<div class="actions"><%=f.submit%> </div>
<%end%>

to_do_list/app/views/lists/edit.html.erb
<h1>Edit this Task</h1>
<%= render 'form'%>

to_do_list/app/views/lists/index.html.erb
<h1>Bottomless ToDo List</h1>
<%= link_to "New List", new_list_path %> 
<% @lists.each do |list| %> 
<h3><%= link_to list.task, list %></h3>
<h4>Complete?<%= list.complete %></h4>
<div><h4>Due on<%=list.due_date%></h4></div>
<%= link_to "Edit List", edit_list_path(list)%>
<%= link_to 'destroy list', List, method: :delete, data: { confirm: "Are you sure your really done with the task, and not sweeping it under the rug?"} %>
<%end%>

to_do_list/app/views/lists/new.html.erb
<h1>Add A New Task</h1>
<%= render 'form'%>

to_do_list/app/views/lists/show.html.erb
<h1>Task Details</h1>

<div><%=@list.task %></div>
<div><%=@list.due_date %></div>
<div><%=@list.created_at %></div>
<div><%=@list.complete %></div>
<div><%=@list.notes %></div>
<div><%=@list.catagory %></div>